# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gherkin}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Sassak", "Gregory Hnatiuk", "Aslak Helles\303\270y"]
  s.date = %q{2009-11-09}
  s.description = %q{A fast Gherkin lexer in Ragel}
  s.email = %q{cukes@googlegroups.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "cucumber.yml",
     "ext/gherkin_parser/.gitignore",
     "ext/gherkin_parser/ext_help.h",
     "ext/gherkin_parser/extconf.rb",
     "ext/gherkin_parser/gherkin_parser.c",
     "ext/gherkin_parser/gherkin_parser.h",
     "features/c_feature_policy.feature",
     "features/c_parser.feature",
     "features/feature_parser.feature",
     "features/step_definitions/gherkin_steps.rb",
     "features/steps_parser.feature",
     "features/support/env.rb",
     "gherkin.gemspec",
     "lib/.gitignore",
     "lib/gherkin.rb",
     "lib/gherkin/feature.rb",
     "lib/gherkin/i18n.yml",
     "lib/gherkin/lexer.rb",
     "lib/gherkin/lexer/.gitignore",
     "lib/gherkin/lexer/README.rdoc",
     "lib/gherkin/lexer/ar.rb",
     "lib/gherkin/lexer/bg.rb",
     "lib/gherkin/lexer/cat.rb",
     "lib/gherkin/lexer/cy.rb",
     "lib/gherkin/lexer/cz.rb",
     "lib/gherkin/lexer/da.rb",
     "lib/gherkin/lexer/de.rb",
     "lib/gherkin/lexer/en-au.rb",
     "lib/gherkin/lexer/en-lol.rb",
     "lib/gherkin/lexer/en-tx.rb",
     "lib/gherkin/lexer/en.rb",
     "lib/gherkin/lexer/es.rb",
     "lib/gherkin/lexer/et.rb",
     "lib/gherkin/lexer/fi.rb",
     "lib/gherkin/lexer/fr.rb",
     "lib/gherkin/lexer/he.rb",
     "lib/gherkin/lexer/hr.rb",
     "lib/gherkin/lexer/hu.rb",
     "lib/gherkin/lexer/id.rb",
     "lib/gherkin/lexer/it.rb",
     "lib/gherkin/lexer/ja.rb",
     "lib/gherkin/lexer/ko.rb",
     "lib/gherkin/lexer/lt.rb",
     "lib/gherkin/lexer/lv.rb",
     "lib/gherkin/lexer/nl.rb",
     "lib/gherkin/lexer/no.rb",
     "lib/gherkin/lexer/pl.rb",
     "lib/gherkin/lexer/pt.rb",
     "lib/gherkin/lexer/ro.rb",
     "lib/gherkin/lexer/ro2.rb",
     "lib/gherkin/lexer/ru.rb",
     "lib/gherkin/lexer/se.rb",
     "lib/gherkin/lexer/sk.rb",
     "lib/gherkin/lexer/sr-Latn.rb",
     "lib/gherkin/lexer/sr.rb",
     "lib/gherkin/lexer/table.rb",
     "lib/gherkin/lexer/tr.rb",
     "lib/gherkin/lexer/uz.rb",
     "lib/gherkin/lexer/vi.rb",
     "lib/gherkin/lexer/zh-CN.rb",
     "lib/gherkin/lexer/zh-TW.rb",
     "lib/gherkin/states.rb",
     "lib/gherkin/states/examples_state.rb",
     "lib/gherkin/states/feature_state.rb",
     "lib/gherkin/states/scenario_outline_state.rb",
     "lib/gherkin/states/scenario_state.rb",
     "lib/gherkin/states/state.rb",
     "lib/gherkin/states/steps_state.rb",
     "lib/gherkin/steps.rb",
     "lib/gherkin/syntax_policy.rb",
     "ragel/i18n/.gitignore",
     "ragel/lexer.c.rl.erb",
     "ragel/lexer.rb.rl.erb",
     "ragel/lexer_common.rl.erb",
     "spec/gherkin/c_lexer_spec.rb",
     "spec/gherkin/fixtures/complex.feature",
     "spec/gherkin/fixtures/i18n_no.feature",
     "spec/gherkin/fixtures/i18n_zh-CN.feature",
     "spec/gherkin/fixtures/simple.feature",
     "spec/gherkin/fixtures/simple_with_comments.feature",
     "spec/gherkin/fixtures/simple_with_tags.feature",
     "spec/gherkin/i18n_spec.rb",
     "spec/gherkin/rb_lexer_spec.rb",
     "spec/gherkin/sexp_recorder.rb",
     "spec/gherkin/shared/lexer_spec.rb",
     "spec/gherkin/shared/py_string_spec.rb",
     "spec/gherkin/shared/table_spec.rb",
     "spec/gherkin/shared/tags_spec.rb",
     "spec/gherkin/states/examples_state_spec.rb",
     "spec/gherkin/states/feature_state_spec.rb",
     "spec/gherkin/states/scenario_outline_state_spec.rb",
     "spec/gherkin/states/scenario_state_spec.rb",
     "spec/gherkin/states/spec_helper.rb",
     "spec/gherkin/states/steps_spec.rb",
     "spec/gherkin/syntax_policy_spec.rb",
     "spec/spec_helper.rb",
     "tasks/bench.rake",
     "tasks/bench/feature_builder.rb",
     "tasks/bench/generated/.gitignore",
     "tasks/bench/null_listener.rb",
     "tasks/cucumber.rake",
     "tasks/ext.rake",
     "tasks/ragel.rake",
     "tasks/rdoc.rake",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/aslakhellesoy/gherkin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Fast Gherkin lexer}
  s.test_files = [
    "spec/gherkin/c_lexer_spec.rb",
     "spec/gherkin/i18n_spec.rb",
     "spec/gherkin/rb_lexer_spec.rb",
     "spec/gherkin/sexp_recorder.rb",
     "spec/gherkin/shared/lexer_spec.rb",
     "spec/gherkin/shared/py_string_spec.rb",
     "spec/gherkin/shared/table_spec.rb",
     "spec/gherkin/shared/tags_spec.rb",
     "spec/gherkin/states/examples_state_spec.rb",
     "spec/gherkin/states/feature_state_spec.rb",
     "spec/gherkin/states/scenario_outline_state_spec.rb",
     "spec/gherkin/states/scenario_state_spec.rb",
     "spec/gherkin/states/spec_helper.rb",
     "spec/gherkin/states/steps_spec.rb",
     "spec/gherkin/syntax_policy_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

