# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gherkin}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Sassak", "Gregory Hnatiuk", "Aslak Helles\303\270y"]
  s.date = %q{2009-11-21}
  s.description = %q{A fast Gherkin lexer in Ragel}
  s.email = %q{cukes@googlegroups.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "cucumber.yml",
     "ext/gherkin_lexer/.gitignore",
     "ext/gherkin_lexer/extconf.rb",
     "features/feature_parser.feature",
     "features/native_lexer.feature",
     "features/parser_with_native_lexer.feature",
     "features/step_definitions/gherkin_steps.rb",
     "features/steps_parser.feature",
     "features/support/env.rb",
     "gherkin.gemspec",
     "java/.gitignore",
     "java/Gherkin.iml",
     "java/build.xml",
     "java/src/gherkin/Lexer.java",
     "java/src/gherkin/LexingError.java",
     "java/src/gherkin/Listener.java",
     "java/src/gherkin/ParseError.java",
     "java/src/gherkin/Parser.java",
     "java/src/gherkin/lexer/.gitignore",
     "java/test/gherkin/ParserTest.java",
     "lib/.gitignore",
     "lib/gherkin.rb",
     "lib/gherkin/c_lexer.rb",
     "lib/gherkin/i18n.yml",
     "lib/gherkin/java_lexer.rb",
     "lib/gherkin/lexer.rb",
     "lib/gherkin/parser.rb",
     "lib/gherkin/parser/comment.txt",
     "lib/gherkin/parser/root.txt",
     "lib/gherkin/rb_lexer.rb",
     "lib/gherkin/rb_lexer/.gitignore",
     "lib/gherkin/rb_lexer/README.rdoc",
     "lib/gherkin/rb_parser.rb",
     "ragel/i18n/.gitignore",
     "ragel/lexer.c.rl.erb",
     "ragel/lexer.java.rl.erb",
     "ragel/lexer.rb.rl.erb",
     "ragel/lexer_common.rl.erb",
     "spec/gherkin/c_lexer_spec.rb",
     "spec/gherkin/fixtures/complex.feature",
     "spec/gherkin/fixtures/i18n_fr.feature",
     "spec/gherkin/fixtures/i18n_no.feature",
     "spec/gherkin/fixtures/i18n_zh-CN.feature",
     "spec/gherkin/fixtures/simple.feature",
     "spec/gherkin/fixtures/simple_with_comments.feature",
     "spec/gherkin/fixtures/simple_with_tags.feature",
     "spec/gherkin/i18n_spec.rb",
     "spec/gherkin/java_lexer_spec.rb",
     "spec/gherkin/parser_spec.rb",
     "spec/gherkin/rb_lexer_spec.rb",
     "spec/gherkin/sexp_recorder.rb",
     "spec/gherkin/shared/lexer_spec.rb",
     "spec/gherkin/shared/py_string_spec.rb",
     "spec/gherkin/shared/table_spec.rb",
     "spec/gherkin/shared/tags_spec.rb",
     "spec/gherkin/states/examples_state_spec.rb",
     "spec/gherkin/states/feature_state_spec.rb",
     "spec/gherkin/states/scenario_outline_state_spec.rb",
     "spec/gherkin/states/scenario_state_spec.rb",
     "spec/gherkin/states/spec_helper.rb",
     "spec/gherkin/states/steps_spec.rb",
     "spec/spec_helper.rb",
     "tasks/bench.rake",
     "tasks/bench/feature_builder.rb",
     "tasks/bench/generated/.gitignore",
     "tasks/bench/null_listener.rb",
     "tasks/cucumber.rake",
     "tasks/ext.rake",
     "tasks/ragel.rake",
     "tasks/rdoc.rake",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/aslakhellesoy/gherkin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Fast Gherkin lexer}
  s.test_files = [
    "spec/gherkin/c_lexer_spec.rb",
     "spec/gherkin/i18n_spec.rb",
     "spec/gherkin/java_lexer_spec.rb",
     "spec/gherkin/parser_spec.rb",
     "spec/gherkin/rb_lexer_spec.rb",
     "spec/gherkin/sexp_recorder.rb",
     "spec/gherkin/shared/lexer_spec.rb",
     "spec/gherkin/shared/py_string_spec.rb",
     "spec/gherkin/shared/table_spec.rb",
     "spec/gherkin/shared/tags_spec.rb",
     "spec/gherkin/states/examples_state_spec.rb",
     "spec/gherkin/states/feature_state_spec.rb",
     "spec/gherkin/states/scenario_outline_state_spec.rb",
     "spec/gherkin/states/scenario_state_spec.rb",
     "spec/gherkin/states/spec_helper.rb",
     "spec/gherkin/states/steps_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

